service: currency-converter
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
functions:
  convert:
    handler: handler.convert
    events:
      - http:
          path: convert
          method: post
          documentation:
            summary: summary
            description: description
            requestBody:
              description: description
            requestModels:
              application/json: ConvertRequest
          reqValidatorName: ConvertRequestValidator
  currencies:
    handler: handler.currencies
    events:
      - http:
          path: currencies
          method: get
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
custom:
  documentation:
    api:
      info:
        version: v0.0.1
        title: test
        description: desc
    models:
      - name: ConvertRequest
        contentType: application/json
        schema: ${file(models/ConvertRequestSchema.json)}
resources:
  Resources:
    ConvertRequestValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: convert-request-validator
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false
